image: docker:19.03

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs/${CI_JOB_ID}" # Create a cert dir per job

services:
  - docker:19.03-dind

before_script:
  - echo "$DOCKER_TLS_CERTDIR"
  - docker info

build:
  stage: build
  script:
    - echo "tada"
    - docker build -t my-docker-image .
