---
variables:
  # We need this for dind or this fail to connect when performing image build
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/
services:
  - docker:dind

before_script:
  - docker -v