# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: docker:19.03.12

services:
  - docker:19.03.12-dind
 
before_script:
  - echo "Before script section"

after_script:
  - echo "After script section"

build:
  stage: build
  script:
    - echo "Do your build here"
    - pwd
    - ls
    - cat /etc/issue
    - docker ps
    - if [ "$( docker container inspect -f '{{.State.Running}}' vane )" == "true" ]; then docker stop vane; fi
    - docker build -t vane:0.0.1 . --build-arg UID=$(shell id -u) --build-arg GID=$(shell id -g)
    - docker run -t -d --rm --name vane -v pwd:/project vane:0.0.1
    - docker ps

test:
  stage: test
  script:
    - echo "Do a test here"
    - docker exec -i vane ls
    - docker exec -i vane pwd
    - docker exec -i vane bash -c "/usr/local/bin/python3 /project/vane/bin/vane.py"
#    - docker exec -i vane bash -c "cd /project/vane/bin && ./vane.py"


deploy:
  stage: deploy
  script:
    - echo "Do your deploy here"
