# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        name: Check for Linting errors on MarkDown files
        exclude: .github/styles
        files: docs/
        args:
          - --config=.github/.markdownlint.yaml
          - --fix

  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.11.2
    hooks:
      - id: markdown-link-check
        name: Markdown Link Check
        files: docs/
        description: Extracts links from markdown texts and checks they're all alive (i.e. return status 200 OK).
        entry: markdown-link-check
        language: node
        types: [markdown]
        stages: [commit, push, manual]
        args:
          - --quiet
          # Add --config=config.json with config.json file mentioning url patterns to ignore if needed