apiVersion: apps/v1
kind: Deployment
metadata:
  name: vane-cvp
  labels:
    app: vane-cvp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vane-cvp
  template:
    metadata:
      name: vane-cvp
      labels:
        app: vane-cvp
    spec:
      hostNetwork: true
      securityContext:
        runAsUser: 10010
        fsGroup: 10010
      containers:
        - name: vane-cvp
          image: vane-cvp:latest
          imagePullPolicy: Never
          command:
            - sh
            - -c
          args:
            - while true; do sleep 1000; done
          volumeMounts:
            - name: vane-data
              mountPath: /vane-data
          ports:
            - containerPort: 8600
      volumes:
        - name: vane-data
          hostPath:
            path: /cvpi/apps/vane-cvp/vane-data
