name: Build and Deploy Vane site

on:
  push:
    branches:
      - develop


jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      ##### Install required Python Modules and build the website #####
      - run: pip install -r docs/requirements.txt
      - run: mkdocs gh-deploy --force
      