name: cvp-extension-builder
run-name: Build CVP extension RPM package

# Run the unittests when a pull request is merged, and post the coverage
# results badge to the repo page

on:
  push:
    branches:
      - gar-cvp-package
    # branches:
    #   - main

env:
  CVP_BUILD_IMAGE: ghcr.io/aristanetworks/vane-cvp-build:latest
  CVP_IMAGE: vane-cvp
  CVP_IMAGE_FILE: vane-cvp.tar.gz

jobs:

  create_centos_build_container:

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Centos container for creating the RPM images and push to GitHub container registry
        run: |
          docker build -t $CVP_BUILD_IMAGE -f Dockerfile.build-CVP . --build-arg UID=$(id -u) --build-arg GID=$(id -g)
          docker push $CVP_BUILD_IMAGE

  create_cvp_container:

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build the CVP Vane container and save it as a tar.gz file
        run: |
          docker build -t $CVP_IMAGE -f Dockerfile.CVP . --network=host
          docker save $CVP_IMAGE | gzip > $CVP_IMAGE_FILE

      - name: Upload the CVP Vane container tar.gz artifact for later use
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.CVP_IMAGE_FILE }}
          path: ${{ env.CVP_IMAGE_FILE }}
          retention-days: 2

  package_cvp_container:

    # This job depends on the previous two containers being built
    needs: [create_centos_build_container, create_cvp_container]

    runs-on: ubuntu-latest
    container:
      # Build the RPM in the vane-cvp-build container (a centos container to match the
      # CVP environment)
      # Can't use the CVP_BUILD_IMAGE variable here because we are not in an "environment" yet
      image: ghcr.io/aristanetworks/vane-cvp-build:latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download the CVP Vane image file artifact we created in the previous job
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.CVP_IMAGE_FILE }}

      - name: Build the CVP rpm package
        run: |
          RPM_NAME=$(make basename_cvp) >> $GITHUB_ENV
          make rpm-cvp

      # - name: Export the name of the rpm package as an env variable
      #   run: |
      #     RPM_NAME=$(basename rpms/*.rpm) >> $GITHUB_ENV

      - name: Save the rpm package as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.RPM_NAME }}-artifact
          # name: vane-cvp.rpm
          path: rpms/${{ env.RPM_NAME }}
