name: development-ci
run-name: ${{ github.actor }} CI development run

on:
  push:
    # Do not run when merging into develop or master
    branches-ignore:
      - 'develop'
      - 'main'

env:
  POETRY_VERSION: 1.5.1

jobs:
  validate:
    # Run validation checks on the code that has been changed,
    # including checking formatting with Black, and linting checks
    # with flake8 and pylint. Branches cannot be merged into develop
    # unless the validate checks all pass.

    runs-on: ubuntu-latest

    steps:

      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          # architecture: 'x64' # The default

      - name: Display the Python version
        run: python -c "import sys; print(sys.version)"

      # - name: Display github context information
      #   # Prints all the github.<xxx> variables in the workflow log.
      #   # Uncomment if needed for reference
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - name: Install Vane and dependencies
        # Use poetry to install Vane and its dependencies
        #   Later stages that require Vane or dependencies must activate the virtual environment
        #   so we export `source $(poetry env info --path)/bin/activate` as env.poetry_home and
        #   eval that value in the stages that need it
        run: |
          python -m pip install --upgrade pip
          pip install poetry==$POETRY_VERSION
          poetry install
          echo "poetry_home=source $(poetry env info --path)/bin/activate" >> $GITHUB_ENV

      - name: Get fork point
        id: forkpoint
        # List all the commits in branch yet to be applied to develop (git
        # cherry), then take the first one (head) and pull the commit hash from
        # the line (awk), and request the commit hash before that one (git show
        # ... <hash>^1). This gives us the fork point hash. We need to check
        # out the develop branch before doing this, but use "fetch" so we do
        # not change to the develop branch.
        run: |
          git fetch origin develop:develop
          echo "fork=$(git show $(git cherry -v develop | head -n 1 | awk '{ print $2 }')^1 --format=%H | head -n 1)" >> $GITHUB_ENV

      - name: Get changed files
        id: changes
        # Adds all changed files as env.all, and changed python files as env.python
        run: |
          echo "Fork point hash: ${{ env.fork }}"

          echo -e "\n"
          echo "All changed files:"
          git diff --name-only --diff-filter=ACMRT ${{ env.fork }} ${{ github.sha }} || echo '<none>'
          echo "all=$(git diff --name-only --diff-filter=ACMRT ${{ env.fork }} ${{ github.sha }} | xargs)" >> $GITHUB_ENV

          echo -e "\n"
          echo "Changed python files:"
          git diff --name-only --diff-filter=ACMRT ${{ env.fork }} ${{ github.sha }} | grep .py$ || echo '<none>'
          echo "python=$(git diff --name-only --diff-filter=ACMRT ${{ env.fork }} ${{ github.sha }} | grep .py$ | xargs)" >> $GITHUB_ENV

      # Run Black on the whole repo
      - name: Run Black to check the code for formatting problems
        if: ${{ env.python }}
        # If any code needs reformatting, black returns an exit code of 1,
        # which fails the action
        run: |
          eval "${{ env.poetry_home }}"
          black --check ${{ env.python }}

      # Run flake8 on the vane and tests directories
      - name: Lint with flake8
        if: ${{ env.python }}
        run: |
          eval "${{ env.poetry_home }}"
          flake8 ${{ env.python }}

      # Run pylint on the vane and tests directories
      - name: Lint with pylint
        if: ${{ env.python }}
        run: |
          eval "${{ env.poetry_home }}"
          pylint ${{ env.python }}

  pip-install:
    # Validate that the pip installation of Vane works properly

    runs-on: ubuntu-latest

    steps:

      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          # architecture: 'x64' # The default

      - name: Display the Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Vane and dependencies
        # Install Vane using pip
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Check the vane name reported with python setup.py
        run: |
          vane_name=$(python setup.py --name)
          if [[ ! "vane" =~ "$vane_name" ]]; then
            echo "Invalid name reported for Vane application: expected 'vane', received '$vane_name'"
            exit 1
          fi

      - name: Check the vane version reported with python setup.py
        run: |
          version_str=$(grep ^version pyproject.toml | awk -F " " '{print $NF}' | tr -d '"')
          vane_version=$(python setup.py --name)
          if [[ ! "$version_str" =~ "$vane_version" ]]; then
            echo "Invalid version reported for Vane application: expected '$version_str', received '$vane_version'"
            exit 1
          fi

      # - name: Run some basic checks after installation and put the results in the environment for testing
      #   run: |
      #     echo "vane_name=$(python setup.py --name 2>&1)" >> $GITHUB_ENV
      #     echo "vane_version=$(python setup.py --version 2>&1)" >> $GITHUB_ENV
      #     echo "vane_help=$(vane --help 2>&1)" >> $GITHUB_ENV

  unittest:
    # Run the Vane unittests
    #   If the tests pass, coverage will be calculated and reported to the output to be used
    #   by a later job. If the tests fail, the job will fail, coverage will not be calculated,
    #   and the coverage job will not run.

    runs-on: ubuntu-latest

    outputs:
      coverage: ${{ steps.coverage.outputs.coverage }}

    steps:

      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          # architecture: 'x64' # The default

      - name: Display the Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        # Use poetry to install Vane and its dependencies
        #   Later stages that require Vane or dependencies must activate the virtual environment
        #   so we export `source $(poetry env info --path)/bin/activate` as env.poetry_home and
        #   eval that value in the stages that need it
        run: |
          python -m pip install --upgrade pip
          pip install poetry==$POETRY_VERSION
          poetry install
          echo "poetry_home=source $(poetry env info --path)/bin/activate" >> $GITHUB_ENV

      - name: Run the unittests
        # Install vane in "editable/developer" mode, so the executable is using
        # the source files and coverage can monitor the proper directory
        #   If the unit tests fail, we do not continue on to get the coverage
        run: |
          eval "${{ env.poetry_home }}"
          mkdir -p $PWD/tests/unittests/fixtures/reports/results
          pytest --cov-report term-missing --cov=$PWD/vane $PWD/tests/unittests

      - name: Calculate the coverage
        # Get the coverage score and send it to the GITHUB_OUTPUT for the next job to use
        id: coverage
        run: |
          eval "${{ env.poetry_home }}"
          cov_score=$(coverage report | awk '$1 == "TOTAL" {print $NF+0}')
          echo -e "\n----------------"
          echo "Coverage is ${cov_score}%"
          echo -e "----------------\n"
          echo "coverage=${cov_score}" >> $GITHUB_OUTPUT

  coverage:
    # Report the unittest coverage
    # Test coverage is compared with a 90% target goal and the check will fail
    # if below that point.

    runs-on: ubuntu-latest

    needs: unittest

    steps:

      - name: Report the coverage
        # Get the coverage score from the previous unit tests and
        # return success if the value is >= 90
        run: |
          eval "${{ env.poetry_home }}"
          cov_score=${{ needs.unittest.outputs.coverage }}
          echo -e "\n----------------"
          echo "Coverage is ${cov_score}%"
          echo -e "----------------\n"
          [ "${cov_score}" -ge "90" ]
