name: Documentation Testing

# Ensure that documentation is being build and deployed currently
# after the most recent PR

on:
  pull_request:

jobs:

  test_build:
    name: Build site with no warnings
    needs: pre_commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      ##### Install required Python Modules and build the website #####
      - run: pip install -r docs/requirements.txt
      - run: mkdocs build --strict