---
name: "Tag & Release management"
on:
  release:
    types:
      - published

jobs:
  release-doc:
    runs-on: ubuntu-latest
    name: "Publish documentation for release ${{github.ref_name}}"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
    
      - name: 'Build mkdocs content to site folder'
        run: |
          pip install -r docs/requirements.txt
          mike deploy --update-alias --push  ${{github.ref_name}} stable
          mike deploy --update-alias --push  ${{github.ref_name}} latest